name: release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version to bump `package.json` to
      publishtovsm:
        required: false
        description: Publish to VS Marketplace (true/false - default is false)
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo with all histrory and tags
        uses: actions/checkout@v2

      - run: |
          git config --global user.email "onlyutkarsh@users.noreply.github.com"
          git config --global user.name "Utkarsh Shigihalli"

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: 💎 install cached dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 🚧 install dependencies
        run: npm install

      - name: relese-it for marketplace
        if: ${{ github.event.inputs.publishtovsm == true }}
        run: |
          npm run release
          echo "PUBLISH_TO_VSM=true" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: relese-it (prerelease) for testing
        if: ${{ github.event.inputs.publishtovsm == false}}
        run: |
          npm run release -- --preRelease=beta
          echo "PUBLISH_TO_VSM=false" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 compile and create vsix
        run: npm run package

      - name: 🎉 publish to marketplace
        if: ${{ github.event.inputs.publishtovsm == true }}
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ./git-config-user-profiles-*.vsix
          packagePath: ""
